version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  continuous-integration:
    machine: true
    resource_class: jatin-12-2002/newsrunner
    steps:
      - checkout
      - run:
          name: Verify Runner
          command: echo "Hello from the self-hosted runner!"
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          push-image: true
          region: '${AWS_REGION}'
          repo: demo
          registry-id: AWS_ECR_REGISTRY_ID
          repo-scan-on-push: true
          tag: latest

  continuous-delivery:
    machine: true
    resource_class: jatin-12-2002/newsrunner
    steps:
      - checkout

      - aws-cli/setup

      - run:
          name: Authenticate to AWS ECR
          command: |
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - run:
          name: Pull Docker Image from ECR
          command: |
            docker pull ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo:latest

      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 -p 6379:6379 ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo:latest

workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration